allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.5'
  - '@better-auth/drizzle-adapter@1.7.5'
  - '@better-auth/kysely-adapter@1.7.5'
  - '@better-auth/memory-adapter@1.7.5'
  - '@better-auth/mongo-adapter@1.7.5'
  - '@better-auth/prisma-adapter@1.7.5'
  - '@better-auth/telemetry@1.7.5'
  - better-auth@1.7.5
  - '@aws-sdk/client-s3@3.1132.0'
  - '@aws-sdk/s3-request-presigner@3.1132.0'
