"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Mic, Play, Square, Trash2, UploadCloud } from "lucide-react";
import type { SupplierAttachmentView } from "@/lib/bot/types";
import { apiUrl } from "@/lib/api/origin";
import { appApi } from "./api";

export function AudioUploader({ tripId, captureId, onBusyChange, onAttachmentsChange }: { tripId: string; captureId: string; onBusyChange?: (busy: boolean) => void; onAttachmentsChange?: (items: SupplierAttachmentView[]) => void }) {
  const input = useRef<HTMLInputElement>(null); const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const previewUrl = useRef<string | null>(null);
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [recording, setRecording] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [attachments, setAttachments] = useState<SupplierAttachmentView[]>([]);
  function setSelectedFile(next: File | null) { if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); previewUrl.current = next ? URL.createObjectURL(next) : null; setPreview(previewUrl.current); setFile(next); }
  useEffect(() => () => { stream.current?.getTracks().forEach((track) => track.stop()); if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); }, []);
  useEffect(() => { appApi<{ attachments: SupplierAttachmentView[] }>(`/api/bot/captures/${captureId}/attachments?tripId=${encodeURIComponent(tripId)}`).then(({ attachments }) => { const audio = attachments.filter((item) => item.type === "AUDIO"); setAttachments(audio); onAttachmentsChange?.(audio); }).catch(() => undefined); }, [captureId, tripId, onAttachmentsChange]);
  async function record() { try { setError(null); stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); const type = MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : ""; const chunks: BlobPart[] = []; const next = new MediaRecorder(stream.current, type ? { mimeType: type } : undefined); recorder.current = next; next.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); }; next.onstop = () => { const blob = new Blob(chunks, { type: next.mimeType || "audio/webm" }); setSelectedFile(new File([blob], "grabacion.webm", { type: blob.type })); stream.current?.getTracks().forEach((track) => track.stop()); setRecording(false); }; next.start(); setRecording(true); } catch { setError("No pudimos acceder al micrófono. Elegí un audio desde tu dispositivo."); } }
  function stop() { recorder.current?.stop(); }
  function choose(event: ChangeEvent<HTMLInputElement>) { setSelectedFile(event.target.files?.[0] ?? null); setError(null); }
  async function upload() { if (!file || busy) return; setBusy(true); onBusyChange?.(true); setError(null); try { const body = new FormData(); body.set("tripId", tripId); body.set("type", "AUDIO"); body.set("file", file); const response = await fetch(apiUrl(`/api/bot/captures/${captureId}/attachments`), { method: "POST", body, credentials: "include" }); const payload = await response.json() as { attachment?: SupplierAttachmentView; error?: string }; if (!response.ok || !payload.attachment) throw new Error(payload.error ?? "No pudimos subir el audio"); const next = [payload.attachment, ...attachments]; setAttachments(next); onAttachmentsChange?.(next); setSelectedFile(null); if (input.current) input.current.value = ""; } catch (caught) { setError(caught instanceof Error ? caught.message : "No pudimos subir el audio"); } finally { setBusy(false); onBusyChange?.(false); } }
  async function remove(attachment: SupplierAttachmentView) { setBusy(true); onBusyChange?.(true); try { await appApi(`/api/bot/captures/${captureId}/attachments/${attachment.id}?tripId=${encodeURIComponent(tripId)}`, { method: "DELETE" }); const next = attachments.filter((item) => item.id !== attachment.id); setAttachments(next); onAttachmentsChange?.(next); } catch (caught) { setError(caught instanceof Error ? caught.message : "No pudimos borrar el audio"); } finally { setBusy(false); onBusyChange?.(false); } }
  const canRecord = typeof window !== "undefined" && "MediaRecorder" in window && navigator.mediaDevices?.getUserMedia;
  return <div className="rounded-2xl border border-line bg-white p-4 shadow-soft"><h3 className="flex items-center gap-2 text-base"><Mic className="h-5 w-5 text-nihao" />Audio</h3><p className="mt-1 text-xs text-ink-mute">Grabá una nota o elegí WebM, M4A, MP3, WAV u OGG · hasta 25 MB.</p><input ref={input} className="sr-only" type="file" accept="audio/webm,audio/mp4,audio/mpeg,audio/wav,audio/ogg" onChange={choose} /><div className="mt-3 flex gap-2"><button disabled={busy || recording || !canRecord} onClick={() => void record()} type="button" className="app-secondary-button flex-1"><Mic className="h-4 w-4" />{recording ? "Grabando…" : "Grabar audio"}</button>{recording ? <button onClick={stop} type="button" className="app-secondary-button"><Square className="h-4 w-4" />Detener</button> : <button disabled={busy} onClick={() => input.current?.click()} type="button" className="app-secondary-button">Elegir archivo</button>}</div>{file ? <div className="mt-3 rounded-xl bg-paper-soft p-3"><audio controls src={preview ?? undefined} className="w-full" /><div className="mt-2 flex gap-2"><button onClick={() => setSelectedFile(null)} disabled={busy} type="button" className="text-xs font-semibold text-nihao">Descartar</button><button onClick={() => void upload()} disabled={busy} type="button" className="ml-auto text-xs font-semibold text-nihao"><UploadCloud className="mr-1 inline h-4 w-4" />{busy ? "Subiendo…" : "Subir audio"}</button></div></div> : null}{attachments.map((item) => <div key={item.id} className="mt-3 flex items-center gap-2 rounded-xl bg-paper-soft p-3"><Play className="h-4 w-4 text-nihao" /><audio controls src={item.url} className="min-w-0 flex-1" /><button onClick={() => void remove(item)} disabled={busy} aria-label="Eliminar audio" type="button"><Trash2 className="h-4 w-4 text-nihao" /></button></div>)}{error ? <p role="alert" className="mt-3 text-xs text-nihao">{error}</p> : null}</div>;
}
