import test from "node:test";
import assert from "node:assert/strict";
import { canonicalEmail, canonicalPhone, canonicalDomain, compareNames, hasCjk, canonicalOcrCard, compareCard } from "../../lib/channels/whatsapp/card-reconciliation.ts";
import type { CardReading, VisualReading } from "../../lib/channels/whatsapp/ingestion-types.ts";
import type { ExtractionCandidate } from "../../lib/bot/types.ts";
import { BurstReader } from "../../lib/channels/whatsapp/burst-reader.ts";
import type { BurstMessage } from "../../lib/channels/whatsapp/burst-types.ts";
const card = (name = "ABC TECHNOLOGY CO LTD", extra: Partial<CardReading> = {}): CardReading => ({ companyName: name, personName: null, role: null, phones: [], emails: [], websites: [], address: null, visibleText: [], uncertainFields: [], branding: null, ...extra });
const candidate = (name: string | null, extra: Partial<ExtractionCandidate> = {}): ExtractionCandidate => ({ extractedFields: { companyName: name }, evidence: [], reviewFields: [], rawSource: { type: "IMAGE_BUSINESS_CARD" }, ...extra });
for (const label of ["E-mail:", "Email:", "EMAIL:", "Mail:", "Correo:", "E - mail : "]) test(`email canonical label ${label}`, () => { assert.equal(canonicalEmail(`${label}FOO@example.com`), "foo@example.com"); assert.deepEqual(compareCard(card("ABC", { emails: ["foo@example.com"] }), canonicalOcrCard(candidate(null), `${label}FOO@example.com`)).disagreements, []); });
test("email preserves valid local characters and rejects doubtful addresses", () => { assert.equal(canonicalEmail(" <O'Foo+tag@example.com>. "), "o'foo+tag@example.com"); for (const s of ["foo@@example.com", "foo@exa mple.com", "foo..bar@example.com", "foo:bar@example.com", "foo@example"]) assert.equal(canonicalEmail(s), null); });
test("different real emails conflict", () => assert.deepEqual(compareCard(card("ABC", { emails: ["bar@example.com"] }), canonicalOcrCard(candidate(null), "foo@example.com")).disagreements, ["emails"]));
for (const name of ["DRAGINO TECHNOLOGY CO., LTD / 深圳市粹联科技开发有限公司", "深圳市粹联科技开发有限公司 | DRAGINO TECHNOLOGY CO., LTD", "深圳市粹联科技开发有限公司\nDRAGINO TECHNOLOGY CO., LTD", "DRAGINO TECHNOLOGY CO., LTD 深圳市粹联科技开发有限公司"]) test(`bilingual variant ${name}`, () => assert.equal(compareNames(name, "DRAGINO TECHNOLOGY CO LTD"), "BILINGUAL_VARIANT_MATCH"));
test("company punctuation and case only", () => assert.equal(compareNames(" SHENZHEN ABC TECHNOLOGY CO., LTD. ", "shenzhen  abc technology co ltd"), "EXACT_NAME_MATCH"));
test("different identities and multiple Latin companies remain conflicts", () => { assert.equal(compareNames("ABC TECHNOLOGY CO LTD", "XYZ TECHNOLOGY CO LTD"), "NAME_CONFLICT"); assert.equal(compareNames("ABC / XYZ", "ABC"), "NAME_CONFLICT"); assert.equal(compareNames("ABC / 深圳公司 / XYZ", "ABC"), "NAME_CONFLICT"); });
test("CJK detection and person name variants without translation", () => { assert.ok(hasCjk("深圳公司")); assert.ok(!hasCjk("ABC")); assert.equal(compareNames("张伟 / Zhang Wei", "Zhang Wei"), "BILINGUAL_VARIANT_MATCH"); assert.equal(compareNames("张伟", "Zhang Wei"), "NAME_CONFLICT"); assert.equal(compareNames("Сергей / Sergey", "Sergey"), "BILINGUAL_VARIANT_MATCH"); });
test("only Chinese versus English requires identity evidence", () => assert.deepEqual(compareCard(card("ABC"), canonicalOcrCard(candidate("深圳公司"), "深圳公司")).disagreements, ["companyName"]));
test("bilingual name plus exact contacts is compatible", () => { const ocr = "ABC / 深圳公司\nEmail:foo@example.com\nwww.example.com"; const r = compareCard(card("ABC", { emails: ["foo@example.com"], websites: ["https://www.example.com"] }), canonicalOcrCard(candidate("ABC / 深圳公司", { website: "www.example.com" }), ocr)); assert.deepEqual(r.disagreements, []); assert.ok(r.signals.some(s => s.reason === "BILINGUAL_VARIANT_MATCH")); assert.ok(r.signals.some(s => s.reason === "DOMAIN_MATCH")); });
test("two exact contacts can corroborate disjoint scripts but never differing Latin names", () => { const c = candidate("深圳公司", { website: "www.example.com" }); const o = canonicalOcrCard(c, "深圳公司\nfoo@example.com\nwww.example.com"); assert.deepEqual(compareCard(card("ABC", { emails: ["foo@example.com"], websites: ["www.example.com"] }), o).disagreements, []); assert.deepEqual(compareCard(card("ABC", { emails: ["foo@example.com"] }), o).disagreements, ["websites", "companyName"]); });
test("same phone never excuses distinct companies, email or domain", () => { const o = canonicalOcrCard(candidate("ABC", { website: "abc.test", contactMethods: [{ type: "PHONE", rawText: "+86 138-1234-5678" }] }), "ABC\nfoo@abc.test\nabc.test"); const r = compareCard(card("XYZ", { phones: ["+8613812345678"], emails: ["bar@xyz.test"], websites: ["xyz.test"] }), o); assert.deepEqual(r.disagreements, ["emails", "websites", "companyName"]); });
test("phone formatting canonicalizes without changing digits", () => { assert.equal(canonicalPhone("+86 138-1234-5678"), "8613812345678"); const o = canonicalOcrCard(candidate(null, { contactMethods: [{ type: "PHONE", rawText: "+86 138-1234-5678" }] }), ""); assert.deepEqual(compareCard(card("ABC", { phones: ["+8613812345678"] }), o).disagreements, []); assert.deepEqual(compareCard(card("ABC", { phones: ["+8613812345679"] }), o).disagreements, ["phones"]); assert.equal(canonicalPhone("+86x13812345678"), null); });
test("domains stay distinct and preserve hyphens", () => { assert.equal(canonicalDomain("HTTPS://ABC-TOOLS.test/path"), "abc-tools.test"); assert.notEqual(canonicalDomain("abc-tools.test"), canonicalDomain("abctools.test")); });
async function readTwice(first: CardReading, second: CardReading, ocr: string, extracted: ExtractionCandidate) {
  const visuals: VisualReading[] = [first, second].map(c => ({ type: "BUSINESS_CARD", side: "FRONT", confidence: 0.98, readability: "readable", visual: "Card", card: c, product: null })); let calls = 0;
  const objects = new Map<string, Uint8Array>();
  const reader = new BurstReader({ multimodal: true, storage: { async put(i) { objects.set(i.key, Uint8Array.from(i.body as Uint8Array)); }, async get(k) { return new Response(Uint8Array.from(objects.get(k)!)).body; }, async delete() {}, async signedUrl() { return "private"; } }, client: { async getMedia() { return { bytes: new Uint8Array([0xff,0xd8,0xff]), mimeType: "image/jpeg" }; } }, analyzer: { async readImage() { return ocr; }, async segmentAudio(t) { return { segments: [t], confident: true }; } }, transcription: { async transcribe() { throw Error(); } }, extraction: { async extractReading() { return extracted; } }, mistral: { async post() { return { choices: [{ message: { content: JSON.stringify(visuals[Math.min(calls++,1)]) } }] }; } } });
  const m: BurstMessage = { id: "test", sequence: 1, sentAt: null, envelope: { instance: "test", messageId: "test", phone: "123", type: "IMAGE", text: null, sentAt: null, media: { key: { id: "test", remoteJid: "123@s.whatsapp.net", fromMe: false }, message: { imageMessage: {} } } }, reading: null };
  const saved: unknown[] = []; const result = await reader.read(m, async r => { saved.push(structuredClone(r)); }); return { result, calls, saved };
}
test("canonical email avoids unnecessary second vision entirely", async () => { const r = await readTwice(card("ABC", { emails: ["foo@example.com"] }), card(), "ABC\nE-mail:foo@example.com", candidate("ABC")); assert.equal(r.calls,1); assert.equal(r.result.ingestion?.status,"PARSED"); assert.ok(r.result.ingestion?.reconciliation?.first.signals.some(s => s.reason === "EMAIL_CANONICAL_MATCH")); });
test("second vision uses the same canonical OCR and resolves initial uncertain read", async () => { const r = await readTwice(card("ABC", { emails: ["foo@example.com"], uncertainFields: ["emails"] }), card("ABC", { emails: ["foo@example.com"] }), "ABC\nE-mail:foo@example.com", candidate("ABC")); assert.equal(r.calls,2); assert.equal(r.result.ingestion?.status,"PARSED"); assert.deepEqual(r.result.ingestion?.reconciliation?.second?.disagreements,[]); assert.ok(r.saved.length); });
test("second vision confirming a real email conflict remains review", async () => { const r = await readTwice(card("ABC", { emails: ["bar@example.com"] }), card("ABC", { emails: ["bar@example.com"] }), "ABC\nE-mail:foo@example.com", candidate("ABC")); assert.equal(r.calls,2); assert.equal(r.result.ingestion?.error?.type,"AMBIGUOUS_CARD_READING"); assert.deepEqual(r.result.ingestion?.reconciliation?.second?.disagreements,["emails"]); });
test("repeated explicit visual uncertainty remains review", async () => { const c = card("ABC", { uncertainFields: ["companyName"] }); const r = await readTwice(c,c,"ABC",candidate("ABC")); assert.equal(r.result.ingestion?.status,"NEEDS_REVIEW"); });

test("phone plus inside formatting is explicit, not inferred", () => { assert.equal(canonicalPhone("(+86) 15710829907"), "8615710829907"); assert.equal(canonicalPhone("138+12345678"), null); });
test("name spacing around punctuation and symbols", () => assert.equal(compareNames("ABC CO.,LTD.", "ABC CO LTD"), "EXACT_NAME_MATCH"));
test("unknown email labels cannot silently rewrite a local part", () => assert.ok(compareCard(card("ABC", { emails: ["bar@example.com"] }), canonicalOcrCard(candidate(null), "foo:bar@example.com")).disagreements.includes("emails")));

test("valid unpaired local-part punctuation is not stripped", () => { for (const local of ["{foo", "foo}", "!foo", "foo+tag", "o\'foo"]) assert.equal(canonicalEmail(`${local}@example.com`), `${local}@example.com`); });
test("multiple distinct CJK identities are not explained away by shared Latin variant", () => { assert.equal(compareNames("ABC / 深圳甲 / 深圳乙", "ABC"), "NAME_CONFLICT"); assert.equal(compareNames("ABC / 深圳甲", "ABC / 深圳乙"), "NAME_CONFLICT"); });
