import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import pg from "pg";
import { parseNotes, mergeNotes, assertGroundedNotes } from "../../lib/bot/notes.ts";
import { parseProduct, parseSupplierEdit, productRecord, productUpdateData } from "../../lib/bot/supplier-edit.ts";
import { AGENT_TOOLS, agentState, validateToolArgs, type AgentReceipt } from "../../lib/channels/whatsapp/agent-contract.ts";
import { AgentTools } from "../../lib/channels/whatsapp/agent-tools.ts";
import { createAgentEnvironment, localAgentDatabase } from "../../evals/whatsapp-agent/environment.ts";
import type { BurstSnapshot } from "../../lib/channels/whatsapp/burst-types.ts";
import type { ExtractionCandidate } from "../../lib/bot/types.ts";

test("notes are nullable and preserve long free text", () => { assert.equal(parseNotes(undefined),null); assert.equal(parseNotes("  Hace OEM.  "),"Hace OEM."); assert.equal(parseProduct({ name:"Vaso" }).notes,null); assert.equal(parseSupplierEdit({ notes:"Tiene fábrica propia." }).data.notes,"Tiene fábrica propia."); assert.equal(parseNotes("x".repeat(10000)),"x".repeat(10000)); });
test("notes compose without losing previous text or duplicating sentences", () => { assert.equal(mergeNotes("Disponible en amarillo y rojo.","También disponible en azul."),"Disponible en amarillo y rojo.\nTambién disponible en azul."); assert.equal(mergeNotes("Disponible en amarillo y rojo.","disponible en amarillo y rojo"),"Disponible en amarillo y rojo."); assert.equal(mergeNotes("Hace OEM.\nTiene showroom.","Tiene showroom. Hace OEM."),"Hace OEM.\nTiene showroom."); assert.equal(mergeNotes("Previo",null),null); assert.equal(mergeNotes("x".repeat(2048),"Nuevo."),"x".repeat(2048)+"\nNuevo."); });
test("notes cannot duplicate structured facts or infer availability from appearance", () => { for(const value of ["MOQ 500","Lead time: 20 días","Email: foo@example.com","Precio 20 USD","www.example.com","+86 138-1234-5678"]) assert.throws(()=>assertGroundedNotes(value,[value]),/estructurado/); assert.throws(()=>assertGroundedNotes("Disponible en amarillo.",["Foto de un vaso amarillo."]),/evidencia/); assert.throws(()=>assertGroundedNotes("Hace OEM.",["Vaso amarillo."]),/evidencia/); assert.equal(assertGroundedNotes("Disponible en amarillo, rojo y azul.",["Este viene en amarillo, rojo y azul."]),"Disponible en amarillo, rojo y azul."); assert.throws(()=>assertGroundedNotes("Vaso",["Vaso"],["Vaso"]),/estructurado/); });
test("notes strict schema slots use nullable strings and closed objects", () => { for(const name of ["create_supplier_draft","create_product_draft","update_supplier","update_product"]){const tool=AGENT_TOOLS.find(t=>t.function.name===name)!;const schema=tool.function.parameters as {properties:Record<string,unknown>;required:string[];additionalProperties:boolean};const object=(name.startsWith("update")?schema.properties.patch:schema) as typeof schema;assert.equal(tool.function.strict,true);assert.equal(object.additionalProperties,false);assert.ok(object.required.includes("notes"));assert.deepEqual((object.properties.notes as {type:string[]}).type,["string","null"]);} assert.deepEqual(validateToolArgs("update_product",{id:"p",patch:{notes:null,clearFields:[]},evidenceIds:["e"]}).patch,{});assert.deepEqual(validateToolArgs("update_product",{id:"p",patch:{notes:null,clearFields:["notes"]},evidenceIds:["e"]}).patch,{notes:null});assert.throws(()=>validateToolArgs("create_supplier_draft",{tripId:"t",companyId:"c",notes:12,evidenceIds:["e"]}),/inválido/); });
test("historical product objects without notes still serialize/update", () => { const old={id:"p",captureId:"c",supplierId:null,status:"DRAFT" as const,name:"Vaso",sourceText:null,sourceEvidence:[],reviewFields:[],sourceConflicts:[],fobAmount:null,fobCurrency:null,fobUnit:null,fobRawText:null,moqQuantity:null,moqUnit:null,moqNotes:null,moqRawText:null,leadTimeRawText:null,leadTimeDays:null,createdAt:new Date(),updatedAt:new Date()};assert.equal(productRecord(old).notes,null);assert.equal(productUpdateData(old,{name:"Vaso grande"}).notes,null); });

const extraction={async extractReading(text:string):Promise<ExtractionCandidate>{const moq=text.match(/MOQ (\d+)/u);return {extractedFields:{...(text.includes("Nuevo Tools")?{companyName:"Nuevo Tools"}:{}),...(moq?{moq:{quantity:Number(moq[1]),unit:"unidades",notes:null,rawText:moq[0]}}:{})},evidence:[],reviewFields:[],rawSource:{type:"TEXT",text}};}};
test("PostgreSQL: supplier/product notes, grounding, merging and approvals",{skip:!process.env.EVAL_AGENT_DATABASE_URL},async(t)=>{
 const prisma=localAgentDatabase();const env=await createAgentEnvironment(prisma,{trips:[{id:"trip",name:"China",companies:[{id:"company",name:"Demo"}],suppliers:[{id:"base",captureId:"base-capture",companyId:"company",name:"BaseSupplier",city:null}]}]});
 async function setup(text:string,kind:"TEXT"|"AUDIO"="TEXT"){
  await prisma.whatsAppBurst.updateMany({where:{userId:env.userId},data:{status:"DONE"}});
  const id=randomUUID();const snapshot:BurstSnapshot={id:randomUUID(),instance:"test",phone:"123",userId:env.userId,revision:1,leaseId:"lease",status:"PROCESSING",state:{tripId:null,groups:[],question:null,controlIds:[],pendingRefs:[]},messages:[{id,sequence:1,sentAt:null,envelope:{instance:"test",messageId:id,phone:"123",type:kind,text:kind==="TEXT"?text:null,media:null,sentAt:null},reading:{complete:true,...(kind==="AUDIO"?{transcript:text}:{}),segments:[{id:id+":1",text}]}}]};await env.persist(snapshot);const state=agentState(snapshot.state);snapshot.state=state;const tools=new AgentTools({domain:env.domain,extraction,catalog:env.catalog,async checkpoint(next){snapshot.state=next;await env.save(snapshot,next);}});
  const prepare=async()=>{const r=await tools.execute("prepare_evidence",{sources:[{messageId:id,quote:null,role:"FACTS"}]},snapshot,state) as {evidence:Array<{id:string}>};return r.evidence.map(e=>e.id);};return{snapshot,state,tools,prepare};
 }
 type Setup=Awaited<ReturnType<typeof setup>>;
 async function product(s:Setup,notes:string|null){await s.tools.execute("get_supplier",{id:env.id("base")},s.snapshot,s.state);return s.tools.execute("create_product_draft",{supplierId:env.id("base"),name:"Vaso",notes,evidenceIds:await s.prepare()},s.snapshot,s.state) as Promise<AgentReceipt>;}
 async function update(p:string,text:string,notes:string|null){const s=await setup(text);await s.tools.execute("get_product",{id:p},s.snapshot,s.state);const r=await s.tools.execute("update_product",{id:p,patch:{notes},evidenceIds:await s.prepare()},s.snapshot,s.state) as AgentReceipt;return{s,r};}
 async function approve(s:Setup,r:AgentReceipt){await prisma.whatsAppBurstReply.create({data:{burstId:s.snapshot.id,revision:s.snapshot.revision,text:s.state.question!,status:"SENT"}});await env.domain.displayed(s.snapshot,r.operationId);s.snapshot.revision++;const id=randomUUID();s.snapshot.messages.push({id,sequence:s.snapshot.revision,sentAt:null,envelope:{instance:"test",messageId:id,phone:"123",type:"TEXT",text:"sí",media:null,sentAt:null},reading:{complete:true,segments:[]}});await prisma.whatsAppBurst.update({where:{id:s.snapshot.id},data:{revision:s.snapshot.revision}});return env.domain.resolve(s.snapshot,r.operationId,false);}
 try{
  await t.test("create Vaso with three explicit colours and get_product notes",async()=>{const s=await setup("Producto Vaso para BaseSupplier. Disponible en amarillo, rojo y azul.");const r=await product(s,"Disponible en amarillo, rojo y azul.");const p=await prisma.supplierProduct.findUniqueOrThrow({where:{id:r.id}});assert.equal(p.name,"Vaso");assert.equal(p.notes,"Disponible en amarillo, rojo y azul.");const got=await s.tools.execute("get_product",{id:p.id},s.snapshot,s.state) as {data:{notes:string}};assert.equal(got.data.notes,p.notes);});
  await t.test("MOQ stays structured and colours only in notes",async()=>{const s=await setup("Producto Vaso para BaseSupplier. MOQ 500. Disponible en amarillo y azul.");const r=await product(s,"Disponible en amarillo y azul.");const p=await prisma.supplierProduct.findUniqueOrThrow({where:{id:r.id}});assert.equal(p.moqQuantity,500);assert.equal(p.notes,"Disponible en amarillo y azul.");await assert.rejects(product(s,"MOQ 500. Disponible en amarillo y azul."),/estructurado/);});
  await t.test("new supplier draft stores factory/OEM notes and get_supplier",async()=>{const s=await setup("Nuevo Tools. Tiene fábrica propia y hace OEM.");const r=await s.tools.execute("create_supplier_draft",{tripId:env.id("trip"),companyId:env.id("company"),notes:"Tiene fábrica propia y hace OEM.",evidenceIds:await s.prepare()},s.snapshot,s.state) as AgentReceipt;const got=await s.tools.execute("get_supplier",{id:r.id},s.snapshot,s.state) as {data:{notes:string}};assert.equal(got.data.notes,"Tiene fábrica propia y hace OEM.");assert.equal((await prisma.supplierCapture.findUniqueOrThrow({where:{id:r.captureId}})).notes,got.data.notes);});
  await t.test("associated audio facts supply product notes",async()=>{const s=await setup("Producto Vaso para BaseSupplier. El vaso viene en amarillo, rojo y azul.","AUDIO");const r=await product(s,"Disponible en amarillo, rojo y azul.");const p=await prisma.supplierProduct.findUniqueOrThrow({where:{id:r.id}});assert.ok(p.notes?.includes("amarillo, rojo y azul"));assert.ok((p.sourceEvidence as Array<{role:string}>).some(e=>e.role==="FACTS"));});
  await t.test("draft notes merge, repeat is deduplicated, unrelated edits preserve notes",async()=>{const p=await prisma.supplierProduct.create({data:{captureId:env.id("base-capture"),supplierId:env.id("base"),status:"DRAFT",name:"Vaso",notes:"Disponible en amarillo y rojo."}});await update(p.id,"El Vaso también disponible en azul.","También disponible en azul.");const composed="Disponible en amarillo y rojo.\nTambién disponible en azul.";assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,composed);await update(p.id,"El Vaso también disponible en azul.","También disponible en azul.");assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,composed);await prisma.supplierProduct.update({where:{id:p.id},data:productUpdateData(await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}}),{name:"Vaso grande"})});assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,composed);});
  await t.test("confirmed product notes require approval and proposal displays composed result",async()=>{const p=await prisma.supplierProduct.create({data:{captureId:env.id("base-capture"),supplierId:env.id("base"),status:"CONFIRMED",name:"Vaso",notes:"También disponible con tapa."}});const{s,r}=await update(p.id,"El Vaso permite packaging personalizado.","Permite packaging personalizado.");assert.equal(r.status,"PROPOSED");assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,"También disponible con tapa.");assert.equal((r.data?.patch as {notes:string}).notes,"También disponible con tapa.\nPermite packaging personalizado.");await assert.rejects(env.domain.resolve(s.snapshot,r.operationId,false),/respuesta explícita/);await approve(s,r);assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,"También disponible con tapa.\nPermite packaging personalizado.");});
  await t.test("confirmed supplier notes require the same approval and get returns final notes",async()=>{const s=await setup("BaseSupplier tiene showroom en Shenzhen.");await s.tools.execute("get_supplier",{id:env.id("base")},s.snapshot,s.state);const r=await s.tools.execute("update_supplier",{id:env.id("base"),patch:{notes:"Tiene showroom en Shenzhen."},evidenceIds:await s.prepare()},s.snapshot,s.state) as AgentReceipt;assert.equal(r.status,"PROPOSED");assert.equal((await prisma.supplier.findUniqueOrThrow({where:{id:env.id("base")}})).notes,null);await approve(s,r);assert.equal((await env.domain.get(s.snapshot,"SUPPLIER",env.id("base"))).data.notes,"Tiene showroom en Shenzhen.");});
  await t.test("draft supplier notes compose and persist",async()=>{const s=await setup("Nuevo Tools. Hace OEM.");const r=await s.tools.execute("create_supplier_draft",{tripId:env.id("trip"),companyId:env.id("company"),notes:"Hace OEM.",evidenceIds:await s.prepare()},s.snapshot,s.state) as AgentReceipt;const next=await setup("Nuevo Tools. Tiene fábrica propia.");await next.tools.execute("get_supplier",{id:r.id},next.snapshot,next.state);const changed=await next.tools.execute("update_supplier",{id:r.id,patch:{notes:"Tiene fábrica propia."},evidenceIds:await next.prepare()},next.snapshot,next.state) as AgentReceipt;assert.equal(changed.status,"COMPLETED");assert.equal((await env.domain.get(next.snapshot,"SUPPLIER",r.id)).data.notes,"Hace OEM.\nTiene fábrica propia.");});
  await t.test("notes cannot be grounded exclusively in context or guessed image availability",async()=>{const s=await setup("Producto Vaso para BaseSupplier. Una foto muestra un vaso amarillo.");await assert.rejects(product(s,"Disponible en amarillo."),/evidencia/);const ids=await s.prepare();const e=s.state.agent.evidence.find(e=>e.id===ids[0])!;await assert.rejects(env.domain.write(s.snapshot,{tool:"create_product_draft",tripId:env.id("trip"),companyId:env.id("company"),targetId:env.id("base"),name:"Vaso",notes:"Hace OEM.",evidence:[e,{...e,id:"context",role:"CONTEXT",text:"Hace OEM."}]}),/evidencia/);});
  await t.test("verified associated visual description can be notes but never inferred availability",async()=>{const s=await setup("Producto Vaso para BaseSupplier.");const id=randomUUID();s.snapshot.revision++;s.snapshot.messages.push({id,sequence:s.snapshot.revision,sentAt:null,envelope:{instance:s.snapshot.instance,messageId:id,phone:"123",type:"IMAGE",text:null,media:null,sentAt:null},reading:{complete:true,ocr:"",imageKind:"PRODUCT_IMAGE",productImageVerified:true,segments:[],ingestion:{status:"PARSED",stage:"parsed",attempts:[],loadIds:[],classification:{type:"PRODUCT",side:"UNKNOWN_SIDE",confidence:0.98,readability:"readable",visual:"vaso de vidrio amarillo",card:null,product:{description:"vaso de vidrio amarillo",brand:null,model:null,visibleText:[],packaging:false}}}}});s.snapshot.messages.at(-1)!.reading!.storageKey=`notes/${id}`;s.snapshot.messages.at(-1)!.reading!.mimeType="image/jpeg";await env.storage.put({key:`notes/${id}`,body:new Uint8Array([0xff,0xd8,0xff,1]),contentType:"image/jpeg"});await prisma.whatsAppBurst.update({where:{id:s.snapshot.id},data:{revision:s.snapshot.revision}});await prisma.whatsAppBurstMessage.create({data:{id,burstId:s.snapshot.id,instance:s.snapshot.instance,messageId:id,sequence:s.snapshot.revision,envelope:JSON.parse(JSON.stringify(s.snapshot.messages.at(-1)!.envelope)),reading:JSON.parse(JSON.stringify(s.snapshot.messages.at(-1)!.reading))}});await s.tools.execute("get_supplier",{id:env.id("base")},s.snapshot,s.state);const prepared=await s.tools.execute("prepare_evidence",{sources:s.snapshot.messages.map(m=>({messageId:m.id,quote:null,role:"FACTS"}))},s.snapshot,s.state) as {evidence:Array<{id:string}>};const args={supplierId:env.id("base"),name:"Vaso",evidenceIds:prepared.evidence.map(e=>e.id)};await assert.rejects(s.tools.execute("create_product_draft",{...args,notes:"Disponible en amarillo."},s.snapshot,s.state),/evidencia/);const r=await s.tools.execute("create_product_draft",{...args,notes:"Vaso de vidrio amarillo."},s.snapshot,s.state) as AgentReceipt;assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:r.id}})).notes,"Vaso de vidrio amarillo.");});
  await t.test("empty notes cannot silently clear an existing note",async()=>{const p=await prisma.supplierProduct.create({data:{captureId:env.id("base-capture"),supplierId:env.id("base"),status:"DRAFT",name:"Vaso",notes:"También disponible con tapa."}});await assert.rejects(update(p.id,"Vaso.",""),/Vaciar notes/);await assert.rejects(update(p.id,"Vaso.","Vaso"),/estructurado/);assert.equal((await prisma.supplierProduct.findUniqueOrThrow({where:{id:p.id}})).notes,"También disponible con tapa.");});
  await t.test("historical rows with null notes preserve searches/details",async()=>{const p=await prisma.supplierProduct.create({data:{captureId:env.id("base-capture"),supplierId:env.id("base"),name:"Histórico",status:"DRAFT"}});const s=await setup("Consultar Histórico de BaseSupplier.");assert.equal((await env.domain.get(s.snapshot,"PRODUCT",p.id)).data.notes,null);assert.equal((await env.domain.search(s.snapshot,"PRODUCT",env.id("trip"),"Histórico"))[0].data.notes,null);assert.ok((await env.domain.search(s.snapshot,"SUPPLIER",env.id("trip"),"BaseSupplier")).length);});
  await t.test("supplier notes survive automatic confirmation and are idempotent",async()=>{const s=await setup("Nuevo Tools. Tiene fábrica propia y hace OEM. sales@new.test");const ids=await s.prepare();s.state.agent.evidence[0].candidate.contactMethods=[{type:"EMAIL",rawText:"sales@new.test"}];const args={tripId:env.id("trip"),companyId:env.id("company"),notes:"Tiene fábrica propia y hace OEM.",evidenceIds:ids};const r=await s.tools.execute("create_supplier_draft",args,s.snapshot,s.state) as AgentReceipt;assert.equal(r.resourceStatus,"CONFIRMED");assert.equal((await prisma.supplier.findUniqueOrThrow({where:{id:r.id}})).notes,"Tiene fábrica propia y hace OEM.");assert.deepEqual(await s.tools.execute("create_supplier_draft",args,s.snapshot,s.state),r);});
 }finally{await env.cleanup();await prisma.$disconnect();}
});
test("nullable notes migration preserves historical rows",{skip:!process.env.EVAL_AGENT_DATABASE_URL},async()=>{const url=new URL(process.env.EVAL_AGENT_DATABASE_URL!);assert.ok(["127.0.0.1","localhost"].includes(url.hostname));const c=new pg.Client({connectionString:url.toString()});try{await c.connect();for(const name of ["Supplier","SupplierCapture","SupplierProduct"]){await c.query(`CREATE TEMP TABLE "${name}" (id TEXT)`);await c.query(`INSERT INTO "${name}" VALUES ('historical')`);}await c.query(await readFile('prisma/migrations/20261006193000_supplier_product_notes/migration.sql','utf8'));for(const name of ["Supplier","SupplierCapture","SupplierProduct"]){const r=await c.query(`SELECT notes FROM "${name}"`);assert.equal(r.rows[0].notes,null);}}finally{await c.end();}});
