import type { CanonicalOcrCard, CardComparison } from "./card-reconciliation.ts";
import type { ExtractionCandidate } from "../../bot/types.ts";
import type { AgentQuestion, AgentTerminationReason } from "./agent-contract.ts";

export type EvidenceResolution = { status: "RESOLVED_BY_LATER_EVIDENCE"; originalStatus: AssetStatus; originalError?: AssetIngestion["error"]; resolvedByAssetId: string; resolvedByLoadId: string; resolvedByBurstId: string; resourceId: string; timestamp: string; reason: string; signals: string[] };
export type AssetStatus = "PENDING_RETRY" | "DOWNLOADED" | "OCR_COMPLETED" | "VISION_COMPLETED" | "SECOND_READ_COMPLETED" | "RECEIVED" | "CLASSIFIED" | "PARSED" | "GROUPED" | "PROCESSED" | "NEEDS_REVIEW" | "FAILED";
export type VisualType = "BUSINESS_CARD" | "PRODUCT" | "DOCUMENT" | "OTHER";
export type Readability = "readable" | "partially_readable" | "unreadable" | "ambiguous";
export type CardReading = { companyName: string | null; personName: string | null; role: string | null; phones: string[]; emails: string[]; websites: string[]; address: string | null; visibleText: string[]; uncertainFields: string[]; branding: string | null };
export type ProductObservation = { description: string; brand: string | null; model: string | null; visibleText: string[]; packaging: boolean };
export type VisualReading = { type: VisualType; side: "FRONT" | "BACK" | "UNKNOWN_SIDE"; confidence: number; readability: Readability; visual: string; card: CardReading | null; product: ProductObservation | null };
export type IngestionAttempt = { stage: string; attempt: number; revision: number; errorType?: string; retryable?: boolean };
export type AssetIngestion = { enrichmentVersion?: 1; caption?: import("./reading-enrichment").CaptionExtraction; nameRomanization?: { original: string; latin: string | null }; fallback?: { model: string; reading: VisualReading }; resolution?: EvidenceResolution;  reconciliation?: { version: 1; ocr: CanonicalOcrCard; first: CardComparison; second?: CardComparison }; operational?: { failures: number; nextAttemptAt?: number; durationMs?: number }; readability?: Readability; status: AssetStatus; stage: string; attempts: IngestionAttempt[]; classification?: VisualReading; independentReadings?: VisualReading[]; ocrCandidate?: ExtractionCandidate; trustedText?: string; error?: { type: string; retryable: boolean; stage: string }; loadIds: string[] };
export type EvidenceLink = { sourceAssetId: string; sourceSegmentId?: string; targetLoadId?: string; relationship: "FRONT_OF" | "BACK_OF" | "IMAGE_OF" | "FACTS_FOR" | "CONTEXT_FOR" | "POSSIBLY_RELATED"; confidence: "HIGH" | "MEDIUM" | "AMBIGUOUS"; reasons: string[]; candidateTargets: string[] };
export type LogicalLoad = { supplierContext?: { loadId: string; reason: string; sourceMessageId: string }; resolution?: EvidenceResolution;  operational?: { failures: number; nextAttemptAt?: number }; execution?: { rounds: number; terminationReason?: AgentTerminationReason; revision: number }; resourceId?: string; id: string; type: "SUPPLIER" | "PRODUCT" | "EVIDENCE"; assetIds: string[]; name: string | null; status: AssetStatus; reasons: string[]; question?: AgentQuestion; questionText?: string | null; error?: { type: string; retryable: boolean; stage: string } };
export type GroupingTrace = { assetA: string; assetB: string; signals: { sameCompany: boolean; sameDomain: boolean; samePerson: boolean; samePhone: boolean; sameEmail: boolean; visualBranding: boolean; complementarySide: boolean; sequenceDistance: number }; reasons: string[]; decision: "GROUP" | "DO_NOT_GROUP" | "AMBIGUOUS" };
export type AssociationTrace = { assetId: string; segmentId: string; candidates: Array<{ loadId: string; explicitSupplierName: boolean; visualProductReference: boolean; sequenceDistance: number }>; selectedTarget?: string; reason: string; confidence: "HIGH" | "MEDIUM" | "AMBIGUOUS"; clarificationRequired: boolean };
export type EvidenceGraph = { groupingAttempts?: GroupingTrace[]; associationAttempts?: AssociationTrace[]; version: 1; revision: number; activeLoadId?: string; assets: Array<{ resolution?: EvidenceResolution; id: string; type: "IMAGE" | "AUDIO" | "TEXT" | "DOCUMENT"; status: AssetStatus; classification?: VisualType; readability?: Readability; loadIds: string[]; error?: AssetIngestion["error"] }>; loads: LogicalLoad[]; links: EvidenceLink[]; derivations: Array<{ id: string; type: "OCR" | "TEXT"; sourceAssetId: string; relationship: "DERIVED_FROM" }>; summary: { totalAssets: number; totalLogicalLoads: number; processed: number; resolvedHistorical?: number; pending: number; needsReview: number; failed: number } };
